name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tests with CMake
      run: |
        cd tests
        mkdir _build
        cd _build
        cmake ..
        make -j2
        
    - name: Run tests
      run: |
        cd tests/_build
        ./safechat_tests
